"""
Pattern Matcher Module - Smart data extraction using pattern learning from examples.
"""
import re
from typing import List, Dict, Any, Optional, Tuple


class PatternMatcher:
    """
    Learn patterns from user examples and find matching values in text.
    """
    
    def __init__(self):
        self.patterns: Dict[str, Dict[str, Any]] = {}
    
    def learn_pattern(self, field_name: str, example: str) -> str:
        """
        Create a regex pattern from a user-provided example.
        
        The pattern is generated by analyzing the structure of the example:
        - Digits become \d
        - Letters become [A-Za-z]
        - Spaces preserved
        - Special characters escaped
        
        Args:
            field_name: Name of the field (e.g., "Číslo faktury").
            example: Example value (e.g., "2023001" or "CZ123456").
            
        Returns:
            Generated regex pattern.
        """
        pattern_parts = []
        i = 0
        
        while i < len(example):
            char = example[i]
            
            # Count consecutive similar characters
            if char.isdigit():
                count = 0
                while i < len(example) and example[i].isdigit():
                    count += 1
                    i += 1
                if count > 1:
                    pattern_parts.append(f'\\d{{{count}}}')
                else:
                    pattern_parts.append('\\d')
                    
            elif char.isalpha():
                count = 0
                is_upper = char.isupper()
                while i < len(example) and example[i].isalpha():
                    count += 1
                    i += 1
                if is_upper:
                    if count > 1:
                        pattern_parts.append(f'[A-Z]{{{count}}}')
                    else:
                        pattern_parts.append('[A-Z]')
                else:
                    if count > 1:
                        pattern_parts.append(f'[a-zA-Z]{{{count}}}')
                    else:
                        pattern_parts.append('[a-zA-Z]')
                        
            elif char.isspace():
                pattern_parts.append('\\s+')
                while i < len(example) and example[i].isspace():
                    i += 1
                    
            else:
                # Escape special regex characters
                pattern_parts.append(re.escape(char))
                i += 1
        
        pattern = ''.join(pattern_parts)
        
        # Store the pattern with metadata
        self.patterns[field_name] = {
            'pattern': pattern,
            'example': example,
            'regex': re.compile(pattern, re.IGNORECASE)
        }
        
        return pattern
    
    def learn_flexible_pattern(self, field_name: str, example: str) -> str:
        """
        Create a more flexible pattern that allows for variations.
        
        Args:
            field_name: Name of the field.
            example: Example value.
            
        Returns:
            Generated flexible regex pattern.
        """
        pattern_parts = []
        i = 0
        
        while i < len(example):
            char = example[i]
            
            if char.isdigit():
                # Count digits and allow ±2 variation
                count = 0
                while i < len(example) and example[i].isdigit():
                    count += 1
                    i += 1
                min_count = max(1, count - 2)
                max_count = count + 2
                pattern_parts.append(f'\\d{{{min_count},{max_count}}}')
                    
            elif char.isalpha():
                count = 0
                while i < len(example) and example[i].isalpha():
                    count += 1
                    i += 1
                min_count = max(1, count - 1)
                max_count = count + 2
                pattern_parts.append(f'[a-zA-Z]{{{min_count},{max_count}}}')
                        
            elif char.isspace():
                pattern_parts.append('\\s*')
                while i < len(example) and example[i].isspace():
                    i += 1
                    
            else:
                # Allow optional special characters
                pattern_parts.append(re.escape(char) + '?')
                i += 1
        
        pattern = ''.join(pattern_parts)
        
        self.patterns[field_name] = {
            'pattern': pattern,
            'example': example,
            'regex': re.compile(pattern, re.IGNORECASE),
            'flexible': True
        }
        
        return pattern
    
    def find_matches(self, text: str, field_name: str) -> List[str]:
        """
        Find all values matching the learned pattern for a field.
        
        Args:
            text: Text to search in.
            field_name: Name of the field to match.
            
        Returns:
            List of matching values.
        """
        if field_name not in self.patterns:
            raise ValueError(f"Pole '{field_name}' nebylo definováno.")
        
        regex = self.patterns[field_name]['regex']
        matches = regex.findall(text)
        
        # Remove duplicates while preserving order
        seen = set()
        unique_matches = []
        for match in matches:
            if match not in seen:
                seen.add(match)
                unique_matches.append(match)
        
        return unique_matches
    
    def find_all_matches(self, text: str) -> Dict[str, List[str]]:
        """
        Find matches for all defined patterns.
        
        Args:
            text: Text to search in.
            
        Returns:
            Dictionary mapping field names to lists of matches.
        """
        results = {}
        for field_name in self.patterns:
            results[field_name] = self.find_matches(text, field_name)
        return results
    
    def find_by_label(self, text: str, label: str, max_length: int = 50) -> List[str]:
        """
        Find value that appears after a label/keyword in text.
        
        This is useful for structured documents where values follow labels like:
        "IČ: 12345678" or "Číslo dokladu: 000367"
        
        Args:
            text: Text to search in.
            label: Label to search for (e.g., "IČ", "Číslo dokladu").
            max_length: Maximum length of value to capture.
            
        Returns:
            List of values found after the label.
        """
        results = []
        
        # Create pattern to match label followed by value
        # Allow for various separators: :, =, space, tab
        label_escaped = re.escape(label)
        pattern = rf'{label_escaped}\s*[:=]?\s*([^\n\r]{{1,{max_length}}})'
        
        matches = re.findall(pattern, text, re.IGNORECASE)
        
        # Common labels that indicate end of current value
        stop_labels = ['IČ', 'DIČ', 'IC', 'DIC', 'Sklad', 'Popis', 'Označení', 
                       'Datum', 'Telefon', 'Fax', 'Email', 'E-mail', 'Odběratel',
                       'Dodavatel', 'Číslo', 'Množství', 'Zakázka', 'Řádek']
        
        for match in matches:
            value = match.strip()
            
            # Stop at any label-like pattern (word followed by :)
            # This prevents capturing "IČ: 123 DIČ: 456" as one value
            for stop in stop_labels:
                if stop.lower() != label.lower():  # Don't stop at the label we're searching for
                    # Find where the stop label appears
                    stop_pattern = rf'\s+{re.escape(stop)}\s*[:=]'
                    stop_match = re.search(stop_pattern, value, re.IGNORECASE)
                    if stop_match:
                        value = value[:stop_match.start()].strip()
            
            # Also stop at double spaces or tabs
            value = re.split(r'\s{2,}|\t', value)[0].strip()
            
            # For IČ/DIČ, extract just the number
            if label.lower() in ['ič', 'ičo', 'ic']:
                num_match = re.search(r'(\d{7,8})', value)
                if num_match:
                    value = num_match.group(1)
            elif label.lower() in ['dič', 'dic']:
                num_match = re.search(r'(CZ\d{8,10})', value, re.IGNORECASE)
                if num_match:
                    value = num_match.group(1).upper()
            
            if value and value not in results:
                results.append(value)
        
        return results
    
    def find_by_labels(self, text: str, labels: List[str], max_length: int = 50) -> List[str]:
        """
        Find values that appear after any of the given labels.
        
        Args:
            text: Text to search in.
            labels: List of possible labels (e.g., ["IČ", "IČO", "IC"]).
            max_length: Maximum length of value to capture.
            
        Returns:
            Combined list of unique values found.
        """
        results = []
        seen = set()
        
        for label in labels:
            matches = self.find_by_label(text, label, max_length)
            for match in matches:
                if match not in seen:
                    seen.add(match)
                    results.append(match)
        
        return results
    
    def extract_table_rows(self, text: str, item_pattern: str = None) -> List[Dict[str, str]]:
        """
        Extract table-like data from text.
        
        Looks for numbered rows or rows with specific patterns.
        
        Args:
            text: Text to search in.
            item_pattern: Optional regex pattern to identify item rows.
            
        Returns:
            List of dicts with extracted row data.
        """
        results = []
        lines = text.split('\n')
        
        # Pattern for numbered items (1, 2, 3... or 1., 2., 3...)
        numbered_pattern = re.compile(r'^\s*(\d+)[.)\s]+(.+)$')
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            match = numbered_pattern.match(line)
            if match:
                results.append({
                    'number': match.group(1),
                    'content': match.group(2).strip()
                })
            elif item_pattern:
                if re.search(item_pattern, line):
                    results.append({'content': line})
        
        return results
    
    def extract_delivery_note(self, text: str) -> Dict[str, Any]:
        """
        Smart extraction specifically for Czech delivery notes (dodací listy).
        
        Understands document structure:
        - Supplier info appears before "Odběratel"
        - Customer info appears after "Odběratel"
        - Items are numbered rows
        
        Returns:
            Dict with structured delivery note data.
        """
        result = {
            'cislo_dokladu': None,
            'objednavka': None,
            'datum_porizeni': None,
            'dodavatel_ic': None,
            'dodavatel_dic': None,
            'dodavatel_nazev': None,
            'polozky': []
        }
        
        # Find position of "Odběratel" to separate supplier/customer sections
        odberatel_pos = text.lower().find('odběratel')
        if odberatel_pos == -1:
            odberatel_pos = text.lower().find('odbératel')
        if odberatel_pos == -1:
            odberatel_pos = len(text)
        
        # Supplier section is before Odběratel
        supplier_section = text[:odberatel_pos]
        
        # Extract Číslo dokladu
        cislo_match = re.search(r'(?:Číslo|Císlo)\s*dokladu\s*[:=]?\s*(\d+)', text, re.IGNORECASE)
        if cislo_match:
            result['cislo_dokladu'] = cislo_match.group(1)
        
        # Extract Objednávka
        obj_match = re.search(r'Objedn[áa]vka\s*[:=]?\s*[_]?(\d+)', text, re.IGNORECASE)
        if obj_match:
            result['objednavka'] = obj_match.group(1)
        
        # Extract Datum pořízení
        datum_match = re.search(r'Datum\s*po[řr][íi]zen[íi]\s*[:=]?\s*(\d{1,2}\.\s?\d{1,2}\.\s?\d{4})', text, re.IGNORECASE)
        if datum_match:
            result['datum_porizeni'] = datum_match.group(1).replace(' ', '')
        
        # Extract supplier IČ (first one in supplier section)
        ic_matches = re.findall(r'I[ČC]\s*[:=]?\s*(\d{7,8})', supplier_section, re.IGNORECASE)
        if ic_matches:
            result['dodavatel_ic'] = ic_matches[0]
        
        # Extract supplier DIČ (first one in supplier section)
        dic_matches = re.findall(r'DI[ČC]\s*[:=]?\s*(CZ\d{8,10})', supplier_section, re.IGNORECASE)
        if dic_matches:
            result['dodavatel_dic'] = dic_matches[0].upper()
        
        # Try to extract company name (usually before address)
        # Look for "spol. s r.o." or "s.r.o." or "a.s."
        name_match = re.search(r'([A-Za-zěščřžýáíéůúĚŠČŘŽÝÁÍÉŮÚ\s]+(?:spol\.\s*s\s*r\.o\.|s\.r\.o\.|a\.s\.))', supplier_section, re.IGNORECASE)
        if name_match:
            result['dodavatel_nazev'] = name_match.group(1).strip()
            
        # Extract Supplier Address
        # Strategy: find line with ZIP code in supplier section (5 digits or 3+2)
        # Use word boundaries to avoid matching parts of longer numbers (like 000360)
        zip_match = re.search(r'\b(\d{3}\s?\d{2})\b\s+([^\n\r]+)', supplier_section)
        if zip_match:
            # Helper to clean address line from other fields
            def clean_line(line):
                # Remove common fields usually found on same lines
                patterns = [
                    r'Sklad\s*[:=]?\s*\S+',
                    r'Objedn[áa]vka\s*[:=]?\s*[_]?\d+',
                    r'Číslo\s*dokladu\s*[:=]?\s*\d+',
                    r'Řada\s*dokladu\s*[:=]?\s*\d+',
                    r'Tel\S*', r'Fax\S*', r'E-mail\S*'
                ]
                cleaned = line
                for pat in patterns:
                    cleaned = re.sub(pat, '', cleaned, flags=re.IGNORECASE)
                return cleaned.strip()

            # Find the line containing the ZIP match
            lines = supplier_section.split('\n')
            addr_parts = []
            
            for i, line in enumerate(lines):
                if zip_match.group(1) in line:
                    # Found ZIP line
                    zip_line = clean_line(line)
                    if zip_line:
                        addr_parts.append(zip_line)
                    
                    # Check previous line for street
                    if i > 0:
                        prev = lines[i-1]
                        prev_clean = clean_line(prev)
                        
                        # Avoid adding Name as address if they are adjacent
                        if result['dodavatel_nazev'] and result['dodavatel_nazev'] in prev:
                            pass
                        elif len(prev_clean) > 3: # Ignore short garbage
                            # Insert before ZIP part
                            addr_parts.insert(0, prev_clean)
                    break
            
            result['dodavatel_adresa'] = ", ".join(addr_parts)
            
        # Extract Vystavil (Issuer)
        vystavil_match = re.search(r'Vystavil\s*[:=]?\s*([^\n\r]+)', text, re.IGNORECASE)
        if vystavil_match:
            result['vystavil'] = vystavil_match.group(1).strip()
        
        # Extract items (numbered rows with product codes)
        # Pattern: row number at start of line, followed by code (like W35-00), description, quantity
        # Must have product code format (letter+number or specific pattern)
        item_pattern = re.compile(
            r'^\s*(\d{1,3})\s+([A-Z][A-Z0-9-]+)\s+(.+?)\s+(\d+)\s*(ks|pcs|m|kg|kusy)?',
            re.IGNORECASE | re.MULTILINE
        )
        for match in item_pattern.finditer(text):
            # Skip if it looks like a zip code or date
            line_num = match.group(1)
            if len(line_num) == 3 and int(line_num) > 100:  # Probably zip code like "417"
                continue
            
            result['polozky'].append({
                'radek': line_num,
                'oznaceni': match.group(2),
                'popis': match.group(3).strip(),
                'mnozstvi': match.group(4),
                'jednotka': match.group(5) or 'ks'
            })
        
        return result
    
    def find_with_context(self, text: str, field_name: str, 
                          context_before: int = 20, 
                          context_after: int = 20) -> List[Dict[str, str]]:
        """
        Find matches with surrounding context.
        
        Args:
            text: Text to search in.
            field_name: Name of the field to match.
            context_before: Characters to include before match.
            context_after: Characters to include after match.
            
        Returns:
            List of dicts with 'match', 'context_before', 'context_after'.
        """
        if field_name not in self.patterns:
            raise ValueError(f"Pole '{field_name}' nebylo definováno.")
        
        regex = self.patterns[field_name]['regex']
        results = []
        
        for match in regex.finditer(text):
            start = max(0, match.start() - context_before)
            end = min(len(text), match.end() + context_after)
            
            results.append({
                'match': match.group(),
                'context_before': text[start:match.start()],
                'context_after': text[match.end():end],
                'position': match.start()
            })
        
        return results
    
    def get_pattern_info(self, field_name: str) -> Optional[Dict[str, Any]]:
        """
        Get information about a defined pattern.
        
        Args:
            field_name: Name of the field.
            
        Returns:
            Pattern info dict or None if not found.
        """
        return self.patterns.get(field_name)
    
    def remove_pattern(self, field_name: str) -> bool:
        """
        Remove a defined pattern.
        
        Args:
            field_name: Name of the field to remove.
            
        Returns:
            True if removed, False if not found.
        """
        if field_name in self.patterns:
            del self.patterns[field_name]
            return True
        return False
    
    def clear_patterns(self) -> None:
        """Remove all defined patterns."""
        self.patterns.clear()
    
    def get_all_field_names(self) -> List[str]:
        """Get list of all defined field names."""
        return list(self.patterns.keys())


# Common pattern presets for Czech documents
COMMON_PATTERNS = {
    'ico': r'\d{8}',  # IČO - 8 digits
    'dic': r'CZ\d{8,10}',  # DIČ - CZ + 8-10 digits
    'bank_account': r'\d{1,6}-?\d{2,10}/\d{4}',  # Czech bank account
    'date_cz': r'\d{1,2}\.\s?\d{1,2}\.\s?\d{4}',  # Czech date format
    'date_iso': r'\d{4}-\d{2}-\d{2}',  # ISO date
    'email': r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}',
    'phone_cz': r'(\+420\s?)?\d{3}\s?\d{3}\s?\d{3}',  # Czech phone
    'price': r'\d{1,3}(?:\s?\d{3})*(?:[,.]\d{2})?\s?(?:Kč|CZK|€|EUR)?',
    'zip_cz': r'\d{3}\s?\d{2}',  # Czech ZIP code
}


def get_preset_pattern(pattern_name: str) -> Optional[str]:
    """
    Get a preset pattern by name.
    
    Args:
        pattern_name: Name of the preset pattern.
        
    Returns:
        Regex pattern string or None if not found.
    """
    return COMMON_PATTERNS.get(pattern_name.lower())


def list_preset_patterns() -> List[str]:
    """Get list of available preset pattern names."""
    return list(COMMON_PATTERNS.keys())
